config/routes.rb
MotionCapture::Application.routes.draw do
  root to: "workouts#index"
  resources :workouts 
end

app/models/workout.rb
class Workout < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]

  # GET /workouts
  # GET /workouts.json
  def index
    @workouts = Workout.all

    if params[:reps]
      @name = "Bicep Curls"
      @reps = params[:reps]

    respond_to do |format|
      format.js
    end
    end
  end

  # GET /workouts/1
  # GET /workouts/1.json
  def show
  end

  # GET /workouts/new
  def new
    @workout = Workout.new
  end

  # GET /workouts/1/edit
  def edit
  end

  # POST /workouts
  # POST /workouts.json
  def create
    @workout = Workout.new(workout_params)

    respond_to do |format|
      if @workout.save
        format.html { redirect_to @workout, notice: 'Workout was successfully created.' }
        format.json { render action: 'show', status: :created, location: @workout }
      else
        format.html { render action: 'new' }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workouts/1
  # PATCH/PUT /workouts/1.json
  def update
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to @workout, notice: 'Workout was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout.destroy
    respond_to do |format|
      format.html { redirect_to workouts_url }
      format.json { head :no_content }
    end
  end

  # def android_update 
  #   if params[:reps]
  #     @name = "Bicep Curls"
  #     @reps = params[:reps]

  #     respond_to do |format|
  #       format.js {}
  #     end
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workout_params
      params[:workout]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MotionCapture</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
	<%= csrf_meta_tag %>
</head>
<body>
	<header>
		<h1 class="head"> Motion Capture </h1>
	</header>

<%= yield %>

</body>
</html>

app/views/workouts/_form.html.erb
<%= form_for(@workout) do |f| %>
  <% if @workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
      <% @workout.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workouts/_index.html.erb
  <div class="state">
     Rest Period: 30s
    <div class="state-inactive"> </div>
  </div>
  <% for i in 1..5 do %>
  <div class="exercise">
      <div class="index"> <div class="index-pin"> <%= i %> </div> </div>
      <%= @reps %>
      <div class="name"> reps </div>
      <div class="reps"> reps </div>
      <div class="spin">  </div>
    </ul>
  </div>  
  <% end %>


<script>
alert("hello");
</script>

app/views/workouts/edit.html.erb
<h1>Editing workout</h1>

<%= render 'form' %>

<%= link_to 'Show', @workout %> |
<%= link_to 'Back', workouts_path %>

app/views/workouts/index.html.erb
<section class="workout">
  <div class="state">
     Rest Period: 30s
    <div class="state-inactive"> </div>
  </div>
  <% for i in 1..5 do %>
  <div class="exercise">
      <div class="index"> <div class="index-pin"> <%= i %> </div> </div>
      <div class="name"> Name </div>
      <div class="reps"> Reps </div>
      <div class="spin">  </div>
    </ul>
  </div>  
  <% end %>
</section>

app/views/workouts/index.js.erb
$(document).ready(function(){
	alert("hello");
});

app/views/workouts/new.html.erb
<h1>New workout</h1>

<%= render 'form' %>

<%= link_to 'Back', workouts_path %>

app/views/workouts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_workout_path(@workout) %> |
<%= link_to 'Back', workouts_path %>